apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: schedule-out-date
spec:
  schedule: "*/4 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: out-date
            image: kedk2135/out
          restartPolicy: OnFailure