# Use postgres/example user/password credentials
# docker-compose -f stack.yml up
version: '3.1'
services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  
  mingle:
    image: kedk2135/mingle:v1
    restart: always
    ports:
      - 8089:8080