apiVersion: v1
kind: Service
metadata:
  name: kubia-svc-2
spec:
  selector:
    app: kubia-svc
  ports:
  - name: http
    port: 8098
    targetPort: http
  - name: https
    port: 8099
    targetPort: https
