apiVersion: v1
kind: Pod
metadata:
  name: app-five
  labels:
        FrontEnd: React
        Language: js
        Webpack: v4.0.1
spec:
    containers:
    - name: coreapi
      image: kedk2135/coreapi
      ports:
      - containerPort: 80