apiVersion: v1
kind: Pod
metadata:
  name: app-four
  labels:
        FrontEnd: React
        Language: Js
spec:
    containers:
    - name: coreapi
      image: kedk2135/coreapi
      ports:
      - containerPort: 80