apiVersion: v1
kind: Pod
metadata:
  name: app-six
  labels:
        FrontEnd: Angular
        Language: TypeScript
        Webpack: v5.0.1
spec:
    containers:
    - name: coreapi
      image: kedk2135/coreapi
      ports:
      - containerPort: 80