apiVersion: v1
kind: Pod
metadata:
  name: app-two
  labels:
        FrontEnd: Vue
        Language: TypeScript
        Webpack: v4.0.0
spec:
    containers:
    - name: coreapi
      image: kedk2135/coreapi
      ports:
      - containerPort: 80