apiVersion: v1
kind: Pod
metadata:
  name: app-three
  labels:
        FrontEnd: Angular
        Language: PHP
        Webpack: v4.0.0
spec:
    containers:
    - name: coreapi
      image: kedk2135/coreapi
      ports:
      - containerPort: 80